/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedGovernanceRouteImport } from './routes/_authenticated/governance'
import { Route as AuthenticatedFinopsRouteImport } from './routes/_authenticated/finops'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedProjectsProjectIdBlueprintRouteImport } from './routes/_authenticated/projects.$projectId.blueprint'
import { Route as AuthenticatedProjectsProjectIdAuditRouteImport } from './routes/_authenticated/projects.$projectId.audit'
import { Route as AuthenticatedProjectsProjectIdArchitectureRouteImport } from './routes/_authenticated/projects.$projectId.architecture'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGovernanceRoute = AuthenticatedGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinopsRoute = AuthenticatedFinopsRouteImport.update({
  id: '/finops',
  path: '/finops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdBlueprintRoute =
  AuthenticatedProjectsProjectIdBlueprintRouteImport.update({
    id: '/blueprint',
    path: '/blueprint',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdAuditRoute =
  AuthenticatedProjectsProjectIdAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdArchitectureRoute =
  AuthenticatedProjectsProjectIdArchitectureRouteImport.update({
    id: '/architecture',
    path: '/architecture',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finops': typeof AuthenticatedFinopsRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/new': typeof AuthenticatedNewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/$projectId/architecture': typeof AuthenticatedProjectsProjectIdArchitectureRoute
  '/projects/$projectId/audit': typeof AuthenticatedProjectsProjectIdAuditRoute
  '/projects/$projectId/blueprint': typeof AuthenticatedProjectsProjectIdBlueprintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finops': typeof AuthenticatedFinopsRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/new': typeof AuthenticatedNewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/$projectId/architecture': typeof AuthenticatedProjectsProjectIdArchitectureRoute
  '/projects/$projectId/audit': typeof AuthenticatedProjectsProjectIdAuditRoute
  '/projects/$projectId/blueprint': typeof AuthenticatedProjectsProjectIdBlueprintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finops': typeof AuthenticatedFinopsRoute
  '/_authenticated/governance': typeof AuthenticatedGovernanceRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/projects/$projectId/architecture': typeof AuthenticatedProjectsProjectIdArchitectureRoute
  '/_authenticated/projects/$projectId/audit': typeof AuthenticatedProjectsProjectIdAuditRoute
  '/_authenticated/projects/$projectId/blueprint': typeof AuthenticatedProjectsProjectIdBlueprintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agents'
    | '/compliance'
    | '/dashboard'
    | '/finops'
    | '/governance'
    | '/integrations'
    | '/new'
    | '/settings'
    | '/api/chat'
    | '/projects/$projectId'
    | '/projects/$projectId/architecture'
    | '/projects/$projectId/audit'
    | '/projects/$projectId/blueprint'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agents'
    | '/compliance'
    | '/dashboard'
    | '/finops'
    | '/governance'
    | '/integrations'
    | '/new'
    | '/settings'
    | '/api/chat'
    | '/projects/$projectId'
    | '/projects/$projectId/architecture'
    | '/projects/$projectId/audit'
    | '/projects/$projectId/blueprint'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agents'
    | '/_authenticated/compliance'
    | '/_authenticated/dashboard'
    | '/_authenticated/finops'
    | '/_authenticated/governance'
    | '/_authenticated/integrations'
    | '/_authenticated/new'
    | '/_authenticated/settings'
    | '/api/chat'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/$projectId/architecture'
    | '/_authenticated/projects/$projectId/audit'
    | '/_authenticated/projects/$projectId/blueprint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance': {
      id: '/_authenticated/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthenticatedGovernanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finops': {
      id: '/_authenticated/finops'
      path: '/finops'
      fullPath: '/finops'
      preLoaderRoute: typeof AuthenticatedFinopsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/blueprint': {
      id: '/_authenticated/projects/$projectId/blueprint'
      path: '/blueprint'
      fullPath: '/projects/$projectId/blueprint'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBlueprintRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/audit': {
      id: '/_authenticated/projects/$projectId/audit'
      path: '/audit'
      fullPath: '/projects/$projectId/audit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdAuditRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/architecture': {
      id: '/_authenticated/projects/$projectId/architecture'
      path: '/architecture'
      fullPath: '/projects/$projectId/architecture'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdArchitectureRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdArchitectureRoute: typeof AuthenticatedProjectsProjectIdArchitectureRoute
  AuthenticatedProjectsProjectIdAuditRoute: typeof AuthenticatedProjectsProjectIdAuditRoute
  AuthenticatedProjectsProjectIdBlueprintRoute: typeof AuthenticatedProjectsProjectIdBlueprintRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdArchitectureRoute:
      AuthenticatedProjectsProjectIdArchitectureRoute,
    AuthenticatedProjectsProjectIdAuditRoute:
      AuthenticatedProjectsProjectIdAuditRoute,
    AuthenticatedProjectsProjectIdBlueprintRoute:
      AuthenticatedProjectsProjectIdBlueprintRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinopsRoute: typeof AuthenticatedFinopsRoute
  AuthenticatedGovernanceRoute: typeof AuthenticatedGovernanceRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinopsRoute: AuthenticatedFinopsRoute,
  AuthenticatedGovernanceRoute: AuthenticatedGovernanceRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
