/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSecurityIndexRouteImport } from './routes/_authenticated/security.index'
import { Route as AuthenticatedSecurityZeroTrustRouteImport } from './routes/_authenticated/security.zero-trust'
import { Route as AuthenticatedSecurityThreatModelRouteImport } from './routes/_authenticated/security.threat-model'
import { Route as AuthenticatedSecurityRedTeamRouteImport } from './routes/_authenticated/security.red-team'
import { Route as AuthenticatedSecurityKnowledgeGraphRouteImport } from './routes/_authenticated/security.knowledge-graph'
import { Route as AuthenticatedSecurityFixEngineRouteImport } from './routes/_authenticated/security.fix-engine'
import { Route as AuthenticatedSecurityComplianceRouteImport } from './routes/_authenticated/security.compliance'
import { Route as AuthenticatedSecurityAttackPathsRouteImport } from './routes/_authenticated/security.attack-paths'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects.$projectId.index'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedProjectsProjectIdBlueprintRouteImport } from './routes/_authenticated/projects.$projectId.blueprint'
import { Route as AuthenticatedProjectsProjectIdAuditRouteImport } from './routes/_authenticated/projects.$projectId.audit'
import { Route as AuthenticatedProjectsProjectIdArchitectureRouteImport } from './routes/_authenticated/projects.$projectId.architecture'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityIndexRoute =
  AuthenticatedSecurityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)
const AuthenticatedSecurityZeroTrustRoute =
  AuthenticatedSecurityZeroTrustRouteImport.update({
    id: '/zero-trust',
    path: '/zero-trust',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)
const AuthenticatedSecurityThreatModelRoute =
  AuthenticatedSecurityThreatModelRouteImport.update({
    id: '/threat-model',
    path: '/threat-model',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)
const AuthenticatedSecurityRedTeamRoute =
  AuthenticatedSecurityRedTeamRouteImport.update({
    id: '/red-team',
    path: '/red-team',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)
const AuthenticatedSecurityKnowledgeGraphRoute =
  AuthenticatedSecurityKnowledgeGraphRouteImport.update({
    id: '/knowledge-graph',
    path: '/knowledge-graph',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)
const AuthenticatedSecurityFixEngineRoute =
  AuthenticatedSecurityFixEngineRouteImport.update({
    id: '/fix-engine',
    path: '/fix-engine',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)
const AuthenticatedSecurityComplianceRoute =
  AuthenticatedSecurityComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)
const AuthenticatedSecurityAttackPathsRoute =
  AuthenticatedSecurityAttackPathsRouteImport.update({
    id: '/attack-paths',
    path: '/attack-paths',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsProjectIdBlueprintRoute =
  AuthenticatedProjectsProjectIdBlueprintRouteImport.update({
    id: '/blueprint',
    path: '/blueprint',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdAuditRoute =
  AuthenticatedProjectsProjectIdAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdArchitectureRoute =
  AuthenticatedProjectsProjectIdArchitectureRouteImport.update({
    id: '/architecture',
    path: '/architecture',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new': typeof AuthenticatedNewRoute
  '/security': typeof AuthenticatedSecurityRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/security/attack-paths': typeof AuthenticatedSecurityAttackPathsRoute
  '/security/compliance': typeof AuthenticatedSecurityComplianceRoute
  '/security/fix-engine': typeof AuthenticatedSecurityFixEngineRoute
  '/security/knowledge-graph': typeof AuthenticatedSecurityKnowledgeGraphRoute
  '/security/red-team': typeof AuthenticatedSecurityRedTeamRoute
  '/security/threat-model': typeof AuthenticatedSecurityThreatModelRoute
  '/security/zero-trust': typeof AuthenticatedSecurityZeroTrustRoute
  '/security/': typeof AuthenticatedSecurityIndexRoute
  '/projects/$projectId/architecture': typeof AuthenticatedProjectsProjectIdArchitectureRoute
  '/projects/$projectId/audit': typeof AuthenticatedProjectsProjectIdAuditRoute
  '/projects/$projectId/blueprint': typeof AuthenticatedProjectsProjectIdBlueprintRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new': typeof AuthenticatedNewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/security/attack-paths': typeof AuthenticatedSecurityAttackPathsRoute
  '/security/compliance': typeof AuthenticatedSecurityComplianceRoute
  '/security/fix-engine': typeof AuthenticatedSecurityFixEngineRoute
  '/security/knowledge-graph': typeof AuthenticatedSecurityKnowledgeGraphRoute
  '/security/red-team': typeof AuthenticatedSecurityRedTeamRoute
  '/security/threat-model': typeof AuthenticatedSecurityThreatModelRoute
  '/security/zero-trust': typeof AuthenticatedSecurityZeroTrustRoute
  '/security': typeof AuthenticatedSecurityIndexRoute
  '/projects/$projectId/architecture': typeof AuthenticatedProjectsProjectIdArchitectureRoute
  '/projects/$projectId/audit': typeof AuthenticatedProjectsProjectIdAuditRoute
  '/projects/$projectId/blueprint': typeof AuthenticatedProjectsProjectIdBlueprintRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/security/attack-paths': typeof AuthenticatedSecurityAttackPathsRoute
  '/_authenticated/security/compliance': typeof AuthenticatedSecurityComplianceRoute
  '/_authenticated/security/fix-engine': typeof AuthenticatedSecurityFixEngineRoute
  '/_authenticated/security/knowledge-graph': typeof AuthenticatedSecurityKnowledgeGraphRoute
  '/_authenticated/security/red-team': typeof AuthenticatedSecurityRedTeamRoute
  '/_authenticated/security/threat-model': typeof AuthenticatedSecurityThreatModelRoute
  '/_authenticated/security/zero-trust': typeof AuthenticatedSecurityZeroTrustRoute
  '/_authenticated/security/': typeof AuthenticatedSecurityIndexRoute
  '/_authenticated/projects/$projectId/architecture': typeof AuthenticatedProjectsProjectIdArchitectureRoute
  '/_authenticated/projects/$projectId/audit': typeof AuthenticatedProjectsProjectIdAuditRoute
  '/_authenticated/projects/$projectId/blueprint': typeof AuthenticatedProjectsProjectIdBlueprintRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/new'
    | '/security'
    | '/settings'
    | '/api/chat'
    | '/projects/$projectId'
    | '/security/attack-paths'
    | '/security/compliance'
    | '/security/fix-engine'
    | '/security/knowledge-graph'
    | '/security/red-team'
    | '/security/threat-model'
    | '/security/zero-trust'
    | '/security/'
    | '/projects/$projectId/architecture'
    | '/projects/$projectId/audit'
    | '/projects/$projectId/blueprint'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/new'
    | '/settings'
    | '/api/chat'
    | '/security/attack-paths'
    | '/security/compliance'
    | '/security/fix-engine'
    | '/security/knowledge-graph'
    | '/security/red-team'
    | '/security/threat-model'
    | '/security/zero-trust'
    | '/security'
    | '/projects/$projectId/architecture'
    | '/projects/$projectId/audit'
    | '/projects/$projectId/blueprint'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/new'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/api/chat'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/security/attack-paths'
    | '/_authenticated/security/compliance'
    | '/_authenticated/security/fix-engine'
    | '/_authenticated/security/knowledge-graph'
    | '/_authenticated/security/red-team'
    | '/_authenticated/security/threat-model'
    | '/_authenticated/security/zero-trust'
    | '/_authenticated/security/'
    | '/_authenticated/projects/$projectId/architecture'
    | '/_authenticated/projects/$projectId/audit'
    | '/_authenticated/projects/$projectId/blueprint'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security/': {
      id: '/_authenticated/security/'
      path: '/'
      fullPath: '/security/'
      preLoaderRoute: typeof AuthenticatedSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
    '/_authenticated/security/zero-trust': {
      id: '/_authenticated/security/zero-trust'
      path: '/zero-trust'
      fullPath: '/security/zero-trust'
      preLoaderRoute: typeof AuthenticatedSecurityZeroTrustRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
    '/_authenticated/security/threat-model': {
      id: '/_authenticated/security/threat-model'
      path: '/threat-model'
      fullPath: '/security/threat-model'
      preLoaderRoute: typeof AuthenticatedSecurityThreatModelRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
    '/_authenticated/security/red-team': {
      id: '/_authenticated/security/red-team'
      path: '/red-team'
      fullPath: '/security/red-team'
      preLoaderRoute: typeof AuthenticatedSecurityRedTeamRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
    '/_authenticated/security/knowledge-graph': {
      id: '/_authenticated/security/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/security/knowledge-graph'
      preLoaderRoute: typeof AuthenticatedSecurityKnowledgeGraphRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
    '/_authenticated/security/fix-engine': {
      id: '/_authenticated/security/fix-engine'
      path: '/fix-engine'
      fullPath: '/security/fix-engine'
      preLoaderRoute: typeof AuthenticatedSecurityFixEngineRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
    '/_authenticated/security/compliance': {
      id: '/_authenticated/security/compliance'
      path: '/compliance'
      fullPath: '/security/compliance'
      preLoaderRoute: typeof AuthenticatedSecurityComplianceRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
    '/_authenticated/security/attack-paths': {
      id: '/_authenticated/security/attack-paths'
      path: '/attack-paths'
      fullPath: '/security/attack-paths'
      preLoaderRoute: typeof AuthenticatedSecurityAttackPathsRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$projectId/blueprint': {
      id: '/_authenticated/projects/$projectId/blueprint'
      path: '/blueprint'
      fullPath: '/projects/$projectId/blueprint'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBlueprintRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/audit': {
      id: '/_authenticated/projects/$projectId/audit'
      path: '/audit'
      fullPath: '/projects/$projectId/audit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdAuditRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/architecture': {
      id: '/_authenticated/projects/$projectId/architecture'
      path: '/architecture'
      fullPath: '/projects/$projectId/architecture'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdArchitectureRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedSecurityRouteChildren {
  AuthenticatedSecurityAttackPathsRoute: typeof AuthenticatedSecurityAttackPathsRoute
  AuthenticatedSecurityComplianceRoute: typeof AuthenticatedSecurityComplianceRoute
  AuthenticatedSecurityFixEngineRoute: typeof AuthenticatedSecurityFixEngineRoute
  AuthenticatedSecurityKnowledgeGraphRoute: typeof AuthenticatedSecurityKnowledgeGraphRoute
  AuthenticatedSecurityRedTeamRoute: typeof AuthenticatedSecurityRedTeamRoute
  AuthenticatedSecurityThreatModelRoute: typeof AuthenticatedSecurityThreatModelRoute
  AuthenticatedSecurityZeroTrustRoute: typeof AuthenticatedSecurityZeroTrustRoute
  AuthenticatedSecurityIndexRoute: typeof AuthenticatedSecurityIndexRoute
}

const AuthenticatedSecurityRouteChildren: AuthenticatedSecurityRouteChildren = {
  AuthenticatedSecurityAttackPathsRoute: AuthenticatedSecurityAttackPathsRoute,
  AuthenticatedSecurityComplianceRoute: AuthenticatedSecurityComplianceRoute,
  AuthenticatedSecurityFixEngineRoute: AuthenticatedSecurityFixEngineRoute,
  AuthenticatedSecurityKnowledgeGraphRoute:
    AuthenticatedSecurityKnowledgeGraphRoute,
  AuthenticatedSecurityRedTeamRoute: AuthenticatedSecurityRedTeamRoute,
  AuthenticatedSecurityThreatModelRoute: AuthenticatedSecurityThreatModelRoute,
  AuthenticatedSecurityZeroTrustRoute: AuthenticatedSecurityZeroTrustRoute,
  AuthenticatedSecurityIndexRoute: AuthenticatedSecurityIndexRoute,
}

const AuthenticatedSecurityRouteWithChildren =
  AuthenticatedSecurityRoute._addFileChildren(
    AuthenticatedSecurityRouteChildren,
  )

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdArchitectureRoute: typeof AuthenticatedProjectsProjectIdArchitectureRoute
  AuthenticatedProjectsProjectIdAuditRoute: typeof AuthenticatedProjectsProjectIdAuditRoute
  AuthenticatedProjectsProjectIdBlueprintRoute: typeof AuthenticatedProjectsProjectIdBlueprintRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdArchitectureRoute:
      AuthenticatedProjectsProjectIdArchitectureRoute,
    AuthenticatedProjectsProjectIdAuditRoute:
      AuthenticatedProjectsProjectIdAuditRoute,
    AuthenticatedProjectsProjectIdBlueprintRoute:
      AuthenticatedProjectsProjectIdBlueprintRoute,
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
